theme: jekyll-theme-slate
name: TrayTrend
show_downloads: true
github:
  zip_url: https://github.com/slicke/traytrend/releases/download/v0.31/TrayTrend.zip
  tar_url: https://github.com/slicke/traytrend/releases/download/v0.31/TrayTrend-linux.tgz
